@Common.Libraries.Services.BackgroundJobService.TestApi_HostAddress = http://localhost:5278

GET {{Common.Libraries.Services.BackgroundJobService.TestApi_HostAddress}}/weatherforecast/
Accept: application/json

###
